### PR TITLE
[messagingframework] Update to upstream using DBus.

### PR DESCRIPTION
**Pull request by dcaliste**
I'm not sure the submodule sha is pointing to something accessible, it corresponds to the code pushed to gerrit, currently under review. I'll update it when it will be accepted in gerrit.

@pvuorela, to test it on device, it requires to adjust some patches. So here they come.

### CODE REVIEW

**Comment by pvuorela** [comment]
Looks like this is missing the changes for the .spec file, especially related to the adjusted patch file set.

The submodule is indeed problematic here, but I can separately reset it to your PR on upstream.

**Comment by pvuorela** [comment]
Smoke test with this seems good so far.

**Comment by dcaliste** [comment]
I've updated the spec files with respect to the patch listing.

**Comment by dcaliste** [comment]
Adjusted with the right upstream sha.

**Review by pvuorela — APPROVED** [review]

**Pull request merged**
