### PR TITLE
[messaging-framework] Update to latest upstream, after Qt6 transition…

### PR DESCRIPTION
**Pull request by dcaliste**
…. Contributes to JB#53847

This is a migration of https://git.sailfishos.org/mer-core/messagingframework/merge_requests/59

I've updated it a bit compared to what @chriadam tested. Here are the changes :
* the failure in tst_QMailMessage::fromRfc2822(encoded_words) has already been solved in gerit upstream by Chris, so I imported his solution.
* the failure in tst_QMailStore::addAccount() was already there before the current MR. In fact it's due to a modification I did in the account patch to allow to return success when an account is not found, see https://git.sailfishos.org/mer-core/messagingframework/merge_requests/39 I didn't modified the test accordingly. It's now fixed.

For the two other failing tests, I'm wondering if they were not already failing also before this MR. Sadly, I've no idea how to test these properly. I don't want to run the tests on my device, because the initTestCase() of these starts with `QMailStore::instance()->clearContent();`. I don't want to loose my emails...

@pvuorela and @flypig, you may be interested in this MR. Finally, it was not that much work compared to what I suspected this morning when @flypig and I discussed. That being said, two tests are still failing...

### CODE REVIEW

**Comment by dcaliste** [comment]
I forgot to mentioned, that I also add a revert commit on the two last commits upstream as mentioned by Chris in sailfishos for his tests.

**Comment by dcaliste** [comment]
I've modified a bit the account patch to take into account the errors reported by @chriadam. Hopefully, I solved them.

I tried yesterday on device, while running in a fake HOME, like `HOME=$PWD ./tst_qmailstore`. I spotted the issues and begun to solve them. But then I noticed that a fake HOME was not enough : the databases for mails and accounts were indeed forged ones but I forgot about DBus messages... Running the test seems to emit that accounts are removed (and account ids are messed up between my true accounts and the forged ones) which in turn make some daemon decide to erase all emails associated to the account... All my beloved emails, too bad. Anyway, I don't really want to try it again. So I hope I understood enough of it yesterday to solve these issues blindly.

**Comment by chriadam** [comment]
Now tst_qmailstore, tst_qmailmessage and tst_qmail_listmodels all pass with no failures.  tst_qlogsystem still fails, but can be ignored, as it also fails in vanilla qmf.

Great work, thanks.  I'll merge once @pvuorela has a chance to check this also, once he's back from vacation.

**Comment by pvuorela** [comment]
Looks all good to me.

**Comment by chriadam** [comment]
Note: if you hit the syncqt.pl issue, change that line from `$directory = abs_path($directory);` to `$directory = File::Spec->canonpath($directory);` -- bug in our qt-tools I think.

**Pull request merged**
